#!/bin/sh

date_formatted=$(date "+%a %F %H:%M")

cmus=$(cmus-remote -Q | grep tag | head -n 2 | cut -d' ' -f 3- | paste -sd "-" -)

battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)

